Isite_name: Go Cook Online
site_url: https://tomwillis608.github.io/go-cook/
repo_url: https://github.com/tomwillis608/go-cook
repo_name: go-cook
# Change the source directory from 'docs' to 'cookbook'
docs_dir: 'cookbook'

# The theme that makes it look great on mobile
theme:
  name: material
  # Custom colors - feel free to change!
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs        # Top tabs for desktop
    - navigation.sections    # Grouped sidebar for mobile
    - navigation.top         # "Back to top" button
    - search.suggest         # Smart search
    - search.highlight       # Highlight search terms
    # Auto-title pages based on folder/file names
    - navigation.path
    - navigation.path_indent
    # Ensure immediate browsing across pages
    - navigation.instant
  icon:
    repo: fontawesome/brands/github

nav: [] # Leave empty to let the theme infer the structure
# Python extensions to make your Markdown powerful
markdown_extensions:
  - admonition              # Great for "Chef's Notes" or warnings
  - attr_list               # Allows adding CSS classes to elements
  - pymdownx.details        # Collapsible sections (great for nutrition info)
  - pymdownx.superfences    # Better code blocks (or pre-formatted text)
  - pymdownx.tasklist:      # Checkboxes for ingredients!
      custom_checkbox: true
  - pymdownx.arithmatex:    # TeX for math
      generic: true
  - pymdownx.snippets:
      base_path: [ 'cookbook' ] 
      check_paths: true.     # DRY out some includes
# Custom CSS for recipe formatting
extra_css:
  - stylesheets/recipe.css
# Custom js for keeping the screen on
extra_javascript:
  - cookbook/js/kitchen-mode.js

# Plugins
plugins:
  - search:
      # Limit indexing to just headings (h1, h2, h3) and the first paragraph
      # This is great for large sites where you only need to find the topic.
      separator: '[\s\-,:!=\[\]/]+' # Regex to split words
      lang: en
